config/routes.rb
Rails.application.routes.draw do
  get 'tasklists/create'

  get 'tasklists/destroy'

  #get 'toppages/index'

  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'
  #get 'users/index'
  #get 'users/show'
  #get 'users/new'
  #get 'users/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "tasklists#index"
  root to: "toppages#index"
  
  resources :tasklists

# User
	get "signup", to: "users#new"
	resources :users, only: [:index, :show, :new, :create]
	
# Session
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout",to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
  validates :status, presence: true, length: {maximum: 10}

	belongs_to :user
	validates :user_id, presence: true
	validates :content, presence: true, length: {maximum:255}
end

app/models/user.rb
class User < ApplicationRecord

	validates :name, presence: true, length: {maximum: 50}
	validates :email, presence: true, length: {maximum: 255},
										format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },                         uniqueness: { case_sensitive: false }
	has_secure_password
	has_many :tasklists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	
	include SessionsHelper

	private

	def require_user_logged_in
		unless logged_in?
			redirect_to login_url
		end
	end
	
	def counts(user)
		@count_tasklists = user.tasklists.count
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success]="ログインに成功しました。"
      redirect_to @user
    else
      flash.now[:danger]="ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session[:user_id]=nil
    flash[:success]="ログアウトしました"
    redirect_to root_path
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id]=@user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
	before_action :set_tasklist, only: [:show,:edit,:update, :destroy]
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :edit]
  
  def index
    @tasklists = Tasklist.all.page(params[:page]).per(10)
  end

  def show
  end

	def new
		@tasklist = Tasklist.new
	end

	def create
		@tasklist = current_user.tasklists.build(tasklist_params)
		
		if @tasklist.save
			flash[:success] = "Tasklist が正常に登録されました"
			redirect_to root_url
		else
			@tasklists = current_user.tasklists.order("created_at DESC").page(params[:page])
			flash.now[:danger] = "Tasklist が登録されませんでした"
			render "toppages/index"
		end
	end

	def edit
	end
	
	def destroy
		@tasklist.destroy
		
		flash[:success] = "Task は正常に削除されました"
		redirect_to root_url
	end

	def update
		if @tasklist.update(tasklist_params)
			flash[:success] = "タスクは正常に登録されました"
			redirect_to root_url
		else
			flash.now[:danger] = "タスクは登録されませんでした"
			render :edit
		end
	end

	private
	# Strong 
	def tasklist_params
		params.require(:tasklist).permit(:content, :status)
	end
	
	def set_tasklist
		@tasklist = Tasklist.find(params[:id])
	end
	
	def correct_user
		@tasklist = current_user.tasklists.find_by(id: params[:id])
		unless @tasklist
			redirect_to root_path
		end
	end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @tasklist = current_user.tasklists.build
      @tasklists = current_user.tasklists.order("created_at DESC").page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @tasklists = @user.tasklists.order("created_at DESC").page(params[:page])
    counts @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] ="ユーザを登録しました"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザの登録に失敗しました。"
      render :new
    end
  end
  
 
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = {size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end  
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
	<div class="alert alert-warning">
		<ul>
			<% model.errors.full_message.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_flash_tasklists.html.erb
<% flash.each do |tasklist_type, tasklist| %>
  
  <div class="alert alert-<%= tasklist_type %>">
    <%= tasklist %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<headers>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Kadai Task-list</a></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Set new task", new_tasklist_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My profile", user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Signup", signup_path %></li>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</headers>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Kadai Tasklist</title>
    
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <%= render "layouts/flash_tasklists" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasklists/_form.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-offset-2 col-md-offset-2 col-sm-8 col-md-8 col-lg-offset-3 col-lg-6">
		<%= form_for(tasklist) do |f| %>
			<% if tasklist.errors.any? %>
				<div class="alert alert-warning">
					<ul>
						<% tasklist.errors.full_messages.each do |tasklist| %>
						<li><%= tasklist%></li>
						<% end %>
					</ul>
				</div>
			<% end %>
				
			<div class="form-group">
				<%= f.label :content, "Task" %>
				<%= f.text_field :content, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :status, "Status" %>
				<%= f.text_field :status, class: "form-control" %>
			</div>
			<%= f.submit "Submit", class:"btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/tasklists/_tasklists.html.erb
<ul class="media-list">
  <% tasklists.each do |tasklist| %>
    <% user = tasklist.user %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(current_user, options={size:50}) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= tasklist.created_at %></span>
        </div>
        <div>
          <p>Task: <%= tasklist.content %></p>
          <p>Status: <%=tasklist.status %></p>
        </div>
        <div>
          <% if current_user == tasklist.user %>
            <%= link_to "Delete", tasklist, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
            <%= link_to "Edit", edit_tasklist_url(tasklist.id) ,class:"btn btn-default btn-xs"%>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate tasklists %>
</ul>

app/views/tasklists/create.html.erb
<h1>Tasklists#create</h1>
<p>Find me in app/views/tasklists/create.html.erb</p>

app/views/tasklists/destroy.html.erb
<h1>Tasklists#destroy</h1>
<p>Find me in app/views/tasklists/destroy.html.erb</p>

app/views/tasklists/edit.html.erb
<h1>id:
<%= @tasklist.id %>
のタスク編集ページ</h1>

<%= render "form", tasklist: @tasklist %>

app/views/tasklists/index.html.erb
<h1>タスク一覧</h1>

<% if @tasklists.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>task</th>
        <th>status</th>
      </tr>
    </thead>
    <tbody>
      <% @tasklists.each do |tasklist| %>
        <tr>
          <td><%= link_to tasklist.id, tasklist %></td>
          <td><%= tasklist.content %></td>
          <td><%= tasklist.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @tasklists %>
  </div>
<% end %>

<%= link_to "新規タスクの登録", new_tasklist_path, class: "btn btn-primary" %>

app/views/tasklists/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render "form", tasklist: @tasklist %>

app/views/tasklists/show.html.erb
<h1>id =
<%= @tasklist.id %>
のタスク詳細</h1>

<table class="table table-border">
  <tr>
    <th>id</th>
    <td><%= @tasklist.id %></td>
  </tr>
  <tr>
    <th>Task</th>
    <td><%= @tasklist.content %></td>
  </tr>
  <tr>
    <th>Status</th>
    <td><%= @tasklist.status %></td>
  </tr>
</table>

<%= link_to "このタスクを編集する", edit_tasklist_path(@tasklist), class: "btn btn-default" %>
<%= link_to "このタスクを削除する", @tasklist, method: :delete, data: {confirm: "本当に削除してよろしいですか？"}, class: "btn btn-danger" %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      
    <div class="col-xs-8">
      <%= render "tasklists/tasklists", tasklists: @tasklists, user: @user %>
    </div>
  </div>
<% else %>
  <div class = "center jumbotron">
    <div class="text-center" >
      <h1>Welcome to the tasklist</h1>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, {size:50}) %>" alert="">
        </div>
        <div class="media-body">
          <%= user.name %>
        </div>
        <div>
          <p><%= link_to "View profile", user_path(user) %></p>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= render "users", users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-6">
    
    <%= form_for(@user) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.text_field :password, class:"form-control" %>
      </div>
      
      <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row" >
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user,{size:500}) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= "active" if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Tasklists <span class="badge"><%= @count_tasklists %></span><% end %></li>
      <li><a href="#">Followings</a></li>
      <li><a href="#">Followers</a></li>
    </ul>
    <%= render "tasklists/tasklists", tasklists: @tasklists, user: @user %>
  </div>
</div>